server:
  port: 90
application:
  id: ${ID_ENV:2}
  name: test
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  datasource:
    username: admin
    password: password
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    driver-class-name: org.postgresql.Driver