server:
  port: 90
application:
  id: ${ID_ENV:2}
  name: test
spring:
  datasource:
    username: admin
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver